/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--md-sys-color-primary)',
        onPrimary: 'var(--md-sys-color-on-primary)',
        primaryContainer: 'var(--md-sys-color-primary-container)',
        onPrimaryContainer: 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        onSecondary: 'var(--md-sys-color-on-secondary)',
        secondaryContainer: 'var(--md-sys-color-secondary-container)',
        onSecondaryContainer: 'var(--md-sys-color-on-secondary-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        onTertiary: 'var(--md-sys-color-on-tertiary)',
        tertiaryContainer: 'var(--md-sys-color-tertiary-container)',
        onTertiaryContainer: 'var(--md-sys-color-on-tertiary-container)',
        error: 'var(--md-sys-color-error)',
        onError: 'var(--md-sys-color-on-error)',
        errorContainer: 'var(--md-sys-color-error-container)',
        onErrorContainer: 'var(--md-sys-color-on-error-container)',
        background: 'var(--md-sys-color-background)',
        onBackground: 'var(--md-sys-color-on-background)',
        surface: 'var(--md-sys-color-surface)',
        onSurface: 'var(--md-sys-color-on-surface)',
        surfaceVariant: 'var(--md-sys-color-surface-variant)',
        onSurfaceVariant: 'var(--md-sys-color-on-surface-variant)',
        surfaceContainerLowest: 'var(--md-sys-color-surface-container-lowest)',
        surfaceContainerLow: 'var(--md-sys-color-surface-container-low)',
        surfaceContainer: 'var(--md-sys-color-surface-container)',
        surfaceContainerHigh: 'var(--md-sys-color-surface-container-high)',
        surfaceContainerHighest: 'var(--md-sys-color-surface-container-highest)',
        outline: 'var(--md-sys-color-outline)',
        outlineVariant: 'var(--md-sys-color-outline-variant)',
        shadow: 'var(--md-sys-color-shadow)',
        scrim: 'var(--md-sys-color-scrim)',
        inverseSurface: 'var(--md-sys-color-inverse-surface)',
        inverseOnSurface: 'var(--md-sys-color-inverse-on-surface)',
        inversePrimary: 'var(--md-sys-color-inverse-primary)',
        neutral: {
          bg: 'var(--md-sys-color-background)',
          dark: 'var(--md-sys-color-background)',
        },
      },
      borderColor: {
        primary: 'var(--md-sys-color-primary)',
      },
      fontFamily: {
        sans: ['Inter', '"Noto Sans TC"', 'sans-serif'],
        heading: ['Inter', '"Noto Sans TC"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'h1': 'clamp(3rem, 5vw, 4.5rem)',
        'h2': 'clamp(2.25rem, 4vw, 3rem)',
        'body': 'clamp(1rem, 1.125vw, 1.125rem)',
      },
      maxWidth: {
        'container': '1280px',
      },
      gap: {
        'gutter': '24px',
      },
    },
    screens: {
      'sm': '600px',
      'md': '960px',
      'lg': '1280px',
    },
  },
  plugins: [],
};
